### ISSUE TITLE
Add the notes from the meetup

### ISSUE THREAD

**Issue by dotemacs** [london-el/london-el.github.io#2]
I'd like to add these notes from the previous meetup:

https://gist.github.com/talwrii/b7bf07f9a865d8a33f439c71630a785e

but not sure how to add them, as yet another link under **Previous talks** subheading?

**Comment by Wilfred** [comment]
Seems reasonable to me. We could label it 'notes' on the link.

**Comment by dotemacs** [comment]
Cool, see https://github.com/london-el/london-el.github.io/pull/3
